Added function called newRecord()
dodul/jambura-core pull request #7
Opened 2023-06-06 03:51 UTC by iamtheazizul

2023-06-06 04:40 UTC, shahriar-prepmock commented
@iamtheazizul please change the PR title into this convention. `Ticket Number : Ticket Title.` . For this PR it should be `JAM-5 : Add newRecord() method in jModel`

And we always try to give a meaningful commit message. Here none can understand anything with the message `Added`.

2023-06-07 07:06 UTC, dodul requested changes

2023-06-07 07:06 UTC, dodul commented on jmodel.php
> +    {
```
return $this->table->id() === null;
```

2023-06-07 07:06 UTC, dodul commented on jmodel.php
> +    public function newRecord()
Please change the method name to `isNewRecord()`

2023-06-07 07:06 UTC, dodul commented on jmodel.php
> +    public function newRecord()
Please add return type

2023-06-19 01:15 UTC, dodul commented
please send PR to https://github.com/Prepmock/jambura-core

2023-06-19 01:15 UTC, closed without merging